### ISSUE TITLE
Uncaught TypeError: loginButton is null

### ISSUE THREAD

**Issue by romanw** [totallyrin/servercontroller#1]
When loading the web page in Firefox you get the following error in the console...

Uncaught TypeError: loginButton is null
    <anonymous> https://totallyrin.github.io/servercontroller/login.js:13
[login.js:13:1](https://totallyrin.github.io/servercontroller/login.js)
    <anonymous> https://totallyrin.github.io/servercontroller/login.js:13

I think this is because the script tag loading login.js is in the header, and is therefore being run before the body has finished loading.

Either move the script tag down to just above the </body> tag, or add the defer keyword...

<script src="login.js" defer></script>

**Comment by totallyrin** [comment]
fixed in most recent push; added defer keyword
